### ISSUE TITLE
Missing "Distributed tracing" chapter in the 0.14.0 documentation

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi.github.io#106]
Jaeger tracing support was released in 0.14.0 and the related documentation is merged in the related operator branch `release-0.14.x` but the "Distributed tracing" chapter is not available in the 0.14.0 documentation on the website (it's only in the master).

**Comment by scholzj** [comment]
There are a lot of chapters missing.

**Comment by ppatierno** [comment]
I just noticed this one because I am looking into tracing for the bridge. What are the other ones?

**Comment by scholzj** [comment]
OAuth for example. I think Kafla Exporter as well. Everything what was not
there for the release.
