### ISSUE TITLE
Logo doesn't load over https at https://strimzi.io

### ISSUE THREAD

**Issue by iranzo** [strimzi/strimzi.github.io#110]
I have:

* [x] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting https://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [x] Included the URL of the page my issue is about
* [x] Described what I did see and what I was expecting to see 

![image](https://user-images.githubusercontent.com/312463/68680359-d44cf000-0561-11ea-9191-cd486d6d4a12.png)

https://strimzi.io

**Comment by scholzj** [comment]
I don't seem to have this problem. Can you open the logo image it self? https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/documentation/logo/strimzi.png

It seems to be for whatever reason loaded from GitHub and not through the website. I think we should look into it and change it - maybe that is causing the issue.

**Comment by iranzo** [comment]
Hi,
No, chrome complains on privacy:

![image](https://user-images.githubusercontent.com/312463/68681052-f6933d80-0562-11ea-8f4a-c59a180858eb.png)

**Comment by iranzo** [comment]
I would say that logo should be copied to website repo and served from there locally

**Comment by iranzo** [comment]
Want me to PR it?

**Comment by scholzj** [comment]
That is interesting, because all my browsers seem to trust it. I wonder what TLS certificate is it presenting to you. Mine seems to be the regular GitHub Inc. certificate issues by DigiCert.

Anyway, I totally agree that it should be on the website it self. I will have a look into it.

**Comment by iranzo** [comment]
Seems to be 'plesk' one:

![image](https://user-images.githubusercontent.com/312463/68681452-baaca800-0563-11ea-93f6-8ef8e13f1a56.png)

**Comment by scholzj** [comment]
That is weird. It looks like Plesk highjacks your connections to GitHub? I opened #111 for this - if you want toyu can double check that the logo works fine for you at https://deploy-preview-111--strimzi.netlify.com/

**Comment by iranzo** [comment]
![image](https://user-images.githubusercontent.com/312463/68682082-d82e4180-0564-11ea-9b4b-4254e769faf0.png)

Perfectly

**Comment by scholzj** [comment]
Ok, this should be now fixed. Thanks for raising this.
