### ISSUE TITLE
On mobile the page width is less than half the screen

### ISSUE THREAD

**Issue by tomncooper** [strimzi/strimzi.github.io#190]
On both Firefox (80.1.3) and Chrome (85.0.4183.101) on Android 11 the website renders at less than half the page width. This happens on the main page and blogs on both Firefox and Chrom. However on the documentation pages Firefox seems to render using the whole page width and Chrome seems to use approx 75%.

Firefox:
![Strimzi-site-firefox-mobile](https://user-images.githubusercontent.com/4671291/93783302-724e2400-fc23-11ea-9897-23cd4dc3d7ef.png)

Chrome:
![Strimzi-site-chrome-mobile](https://user-images.githubusercontent.com/4671291/93783285-6d897000-fc23-11ea-8190-fb95359abc7c.png)

The issue is there with the phone in portrait or landscape mode.

**Comment by marekdano** [comment]
I know where the problem is. I can work on the issue.

**Comment by tomncooper** [comment]
That would be amazing! Thank you!
