### ISSUE TITLE
Blog posts should have sharing buttons

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi.github.io#25]
We should provide a way for people sharing on social media (i.e. Twitter, ...) a blog post.

For example : 
https://help.twitter.com/en/using-twitter/add-twitter-share-button
https://mycyberuniverse.com/web/social-media-share-bar-jekyll-blog-website.html
https://superdevresources.com/share-buttons-jekyll/
http://vdaubry.github.io/2014/10/20/add-social-sharing-buttons-with-jekyll/

**Comment by ArieScheurwater** [comment]
Hi @ppatierno, I created a pull request #136 for you to add the share buttons on the blog posts.

**Comment by sjwoodman** [comment]
@ppatierno Presumably this can be closed now?

**Comment by ppatierno** [comment]
Yes, right! Thanks!
