### ISSUE TITLE
Community Post: Strimzi : Master Apache Kafka on Kubernetes

### ISSUE THREAD

**Issue by hrittikhere** [strimzi/strimzi.github.io#255]
Hey, 
I was wondering do you accept community posts like [Master Apache Kafka on Kubernetes](https://www.p3r.one/strimzi-kafka-on-kubernetes/) for the blog section? Thanks! 

I have:

* [X] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting https://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [X] Included the URL of the page my issue is about
* [X] Described what I did see and what I was expecting to see

**Comment by scholzj** [comment]
We do accept blog post from community. However, I'm just not sure if reposting an existing blog post is the best idea, since AFAIK search engines do not like it. So maybe having something new would be better.

CC @strimzi/maintainers

**Comment by ppatierno** [comment]
I agree with @scholzj on this, maybe it would be great having a blog post about how you are using Strimzi in your specific use case.

**Comment by hrittikhere** [comment]
Yeah, I was also thinking about the same. Also, adding canonical URLs to Jekyll sounds to be a bit complicated. I would look through this and maybe send a post on our specific use case soon. Thanks, @scholzj @ppatierno!

/close
