### ISSUE TITLE
Add Back top Feature

### ISSUE THREAD

**Issue by Khushboo288** [strimzi/strimzi.github.io#259]
I can add Scroll to top feature at last of the web page.

**Comment by Khushboo288** [comment]
Hey Plz assign this issue to me if you want this cool feature in your web site. I am hacktoberfest contributer, so assign only if this project is a part of it.

**Comment by scholzj** [comment]
@strimzi/maintainers Anyone has any strong opinions on this?

**Comment by scholzj** [comment]
My understanding is that it would add a link at the end of each page which takes you to the top of the page. TBH it is a bit hard to say how will it look without seeing some design first 🤷‍♂️ .

**Comment by Khushboo288** [comment]
Now , if you want me to add this feature to your webpage ... Assign this issue to me and also ad hactoberfest label to the issue.
