### ISSUE TITLE
Youtube links not working on Join Us page

### ISSUE THREAD

**Issue by JaideepGuntupalli** [strimzi/strimzi.github.io#267]
I was looking into Strimzi and came across the Join Us page where,`<a>` tag, which is serving the Youtube Tutorial link for the playlist, and the Youtube Channel link are not working—looking into the code, I found that it was a misspelling of the `href` attribute as `gref`.

Website Link: https://strimzi.io/join-us/

HTML file where changes need to be done: https://github.com/strimzi/strimzi.github.io/blob/main/_includes/join-us/join-us-contribute-to-strimzi-band.html

Line Numbers: 23 and 79

<br>

I have:

* [X] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting https://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [X] Included the URL of the page my issue is about
* [X] Described what I did see and what I was expecting to see

**Comment by JaideepGuntupalli** [comment]
Can I make a pr to resolve this issue? I will be changing the attributes back to href.

**Comment by sknot-rh** [comment]
Hi. The PR would be really appreciated!
