### ISSUE TITLE
db2 jar for jdbc connector

### ISSUE THREAD

**Issue by dazedavid** [strimzi/strimzi.github.io#290]
I have: problem with loading db2 jar for jdbc connectors.

* [x] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting https://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [x] Included the URL of the page my issue is about
https://strimzi.io/docs/operators/latest/configuring.html#proc-kafka-connect-config-str 
* [x] Described what I did see and what I was expecting to see 

Added  jdbc connectors with following in dockerfile:
RUN echo "===> Installing Snowflake Connector ..." \
    && confluent-hub install --no-prompt snowflakeinc/snowflake-kafka-connector:1.5.3 --component-dir $PLUGIN_INSTALLATION_DIR --worker-configs $WORKER_CONFIG
ADD https://repo1.xxxxx.com/artifactory/xxxx-Releases/com/xxxxx/xxxxxxxx/db2jcc4.jar $PLUGIN_INSTALLATION_DIR/confluentinc-kafka-connect-jdbc/lib/

Was expecting to see that the jar gets loaded while starting the pods in kubernetes  but the it did not load

**Comment by scholzj** [comment]
That probably doesn't have anything to do with Strimzi website. If you have some general questions, you can ask in the discussion of the operators repo (https://github.com/strimzi/operators/discussions) or for example on Slack - see https://github.com/strimzi/operators#getting-help for more info.
