### ISSUE TITLE
Deploy preview for PRs

### ISSUE THREAD

**Issue by reveurguy** [strimzi/strimzi.github.io#339]
We can use the netlify deploy previews for PRs made for this repository that will help in reviewing the changes made in any PR. We can deploy the website on netlify and link this repo to enable the deploy previews ( deploy previews require deployment on netlify).

**Comment by scholzj** [comment]
I'm not sure I follow why did you open this issue. The previews for PRs are already supported.

**Comment by reveurguy** [comment]
oh yeah sorry my bad
