### ISSUE TITLE
The logos of the company (i.e. Strimzi is used by) are not responsive to screen size and have uneven spacing between them.

### ISSUE THREAD

**Issue by UtkarshMishra12** [strimzi/strimzi.github.io#388]
**The logos of the company (i.e. Strimzi is used by) are not responsive to screen size and have uneven spacing between them.**

Screen Recording

Before

https://github.com/strimzi/strimzi.github.io/assets/67385503/409d42a3-9608-415a-be76-6b2e71f9da42

After

https://github.com/strimzi/strimzi.github.io/assets/67385503/4b354bb3-a2ee-4e31-a06d-f98c82d8b59a

* [x] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting https://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [x] Included the URL of the page my issue is about
* [x] Described what I did see and what I was expecting to see

**Comment by scholzj** [comment]
So, could you please open a PR if you know how to fix it? Thanks.

**Comment by UtkarshMishra12** [comment]
@scholzj Sure on it 🚀
