### ISSUE TITLE
Starting OKD page / latest version of the oc binary link broken

### ISSUE THREAD

**Issue by psakar** [strimzi/strimzi.github.io#40]
I have:

* [ x] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting http://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [ x] Included the URL of the page my issue is about
http://strimzi.io/quickstarts/okd/
* [x] Described what I did see and what I was expecting to see 
Link at the end of the first sentence is broken
"This assumes that you have the latest version of the oc binary, which you can get here"
Last word "here" is broken link

**Comment by scholzj** [comment]
Thanks for raising this @psakar ... it should be fixed now.
