### ISSUE TITLE
`strimzi.io` only available over http

### ISSUE THREAD

**Issue by stigsb** [strimzi/strimzi.github.io#46]
Is there a particular reason `strimzi.io` is only available over http?  I am not very comfortable directly using an http helm repo. GitHub pages on custom domains have had https support for some time now: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

I have:

* [X] Checked that the problem is not about the Strimzi documentation.
  Documentation issues (those with URLs starting http://strimzi.io/docs/...) should be reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/new?title=Docs:&labels=documentation).
* [X] Included the URL of the page my issue is about
* [X] Described what I did see and what I was expecting to see

**Comment by scholzj** [comment]
Thanks for raising this. When we started TLS was not available for GitHub pages and I guess we somehow missed the announcement. I should be hopefully fixed now and the [https://strimzi.io](https://strimzi.io) should work now (at least it does for me). Please give it a try.

**Comment by stigsb** [comment]
Works here! Awesome response time, thank you so much! 👍
